"""Regenerate every reported number from results/*.json.

Writes
  results/flyhash.png        the figure
  paper/generated.tex        LaTeX macros and table bodies used by the paper
  results/SUPPLEMENT.md      full robustness grid, power, coverage, mixing
  README.md                  the block between the results markers

so the manuscript, the figure, the supplement and the README cannot drift apart.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .config import ROOT

RES = ROOT / "results"


def _load(name: str) -> dict | None:
    f = RES / name
    return json.loads(f.read_text()) if f.exists() else None


def pct(x: float, d: int = 1) -> str:
    return f"{100 * x:+.{d}f}"


def pval(p: float) -> str:
    return f"{p:.3f}"


def _holm_all(pr: dict) -> float:
    """Holm-adjusted p of the primary size when all five sizes form one family."""
    from .stats import holm
    ps = [r["randomization"]["p_two_sided"] for r in pr["rows"]]
    i = next(j for j, r in enumerate(pr["rows"]) if r["primary"])
    return holm(ps)[i]


def _primary_row(pr: dict) -> dict:
    return next(r for r in pr["rows"] if r["primary"])


# ------------------------------------------------------------------ figure

_BLUE, _ORANGE, _VIOLET = "#2a78d6", "#eb6834", "#4a3aa7"   # validated CVD-safe
_INK, _MUTED, _SURFACE = "#0b0b0b", "#52514e", "#ffffff"


def figure(pr: dict, ar: dict, path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "figure.dpi": 220, "font.size": 9, "axes.labelsize": 9,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.edgecolor": "#b8b7b1", "axes.labelcolor": _MUTED,
        "xtick.color": _MUTED, "ytick.color": _MUTED,
        "figure.facecolor": _SURFACE, "axes.facecolor": _SURFACE})
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.0, 3.1))

    m = ar["metrics"]["euclidean"]
    ks = m["sizes"]
    g = m["gaussian"]
    lines = [("fly hash (connectome)", m["fly"], _BLUE, "-", "o"),
             ("Gaussian, k bits", g["k_bits"]["mean"], _VIOLET, "-", "s"),
             ("Gaussian, storage-matched", g["storage_matched"]["mean"], _VIOLET, "--", "^"),
             ("Gaussian, operation-matched", g["computation_matched"]["mean"], _VIOLET, ":", "v")]
    for label, y, c, ls, mk in lines:
        a1.plot(ks, y, ls, color=c, lw=1.8, marker=mk, ms=4.5,
                markeredgecolor=_SURFACE, markeredgewidth=0.8, label=label)
    leg = a1.legend(loc="lower right", frameon=False, fontsize=7, handlelength=2.2)
    for t in leg.get_texts():
        t.set_color(_MUTED)
    a1.set_xscale("log", base=2)
    a1.set_xticks(ks)
    a1.set_xticklabels(ks)
    a1.set_xlabel("active Kenyon cells k")
    a1.set_ylabel("mean average precision")
    a1.set_title("Fly hash versus Gaussian sign codes", color=_INK, fontsize=9.5, loc="left")
    a1.grid(axis="y", color="#ecebe6", lw=0.7)
    a1.set_axisbelow(True)

    null = np.array(pr["null_scores"])
    real = np.array(pr["real_scores"])
    rng = np.random.default_rng(0)
    for i, k in enumerate(pr["sizes"]):
        rel = 100 * (null[:, i] / null[:, i].mean() - 1)
        xs = i + rng.uniform(-0.28, 0.28, len(rel))
        a2.scatter(xs, rel, s=5, color=_ORANGE, alpha=0.35, linewidths=0)
        r = 100 * (real[i] / null[:, i].mean() - 1)
        a2.scatter([i], [r], s=46, color=_BLUE, marker="D", edgecolors=_SURFACE,
                   linewidths=0.9, zorder=3)
        row = pr["rows"][i]
        a2.annotate(f"p={row['randomization']['p_two_sided']:.2f}", (i, r),
                    xytext=(0, -13), textcoords="offset points", ha="center",
                    fontsize=6.5, color=_BLUE)
    a2.axhline(0, color="#9a9992", lw=0.9)
    a2.set_xticks(range(len(pr["sizes"])))
    a2.set_xticklabels([f"{k}{'*' if k == pr['primary_k'] else ''}" for k in pr["sizes"]])
    a2.set_xlabel("active Kenyon cells k   (* primary)")
    a2.set_ylabel("mAP relative to null mean (%)")
    a2.set_title(f"Connectome among {pr['B']} curveball nulls",
                 color=_INK, fontsize=9.5, loc="left")
    a2.grid(axis="y", color="#ecebe6", lw=0.7)
    a2.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


# ------------------------------------------------------------------ LaTeX

def _mac(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def latex(pr, ar, cv, rb, co) -> str:
    P = pr["projection"]
    row = _primary_row(pr)
    boot = pr["bootstrap"]
    lo, hi = boot["relative_ci"]
    mac = [
        "% Generated by `python -m flypath report` from results/*.json. Do not edit.",
        _mac("NullB", pr["B"]), _mac("BootR", boot["draws"]),
        _mac("NItems", f"{pr['n_items']:,}".replace(",", "{,}")),
        _mac("PrimaryK", pr["primary_k"]),
        _mac("NGlomFull", P["n_glomeruli_full"]),
        _mac("NCellsFull", f"{P['n_cells_full']:,}".replace(",", "{,}")),
        _mac("NGlom", P["n_glomeruli"]),
        _mac("NCells", f"{P['n_cells']:,}".replace(",", "{,}")),
        _mac("NNZ", f"{P['nnz']:,}".replace(",", "{,}")),
        _mac("InputsFull", f"{P['inputs_mean_full']:.2f}"),
        _mac("Inputs", f"{P['inputs_mean']:.2f}"),
        _mac("PNPartners", f"{P['pn_partners_mean']:.2f}"),
        _mac("PNPartnersFull", f"{P.get('pn_partners_mean_full', P['pn_partners_mean']):.2f}"),
        _mac("FanMin", P["fan_out_min"]), _mac("FanMax", P["fan_out_max"]),
        _mac("FanMaxGlom", P["fan_out_max_glomerulus"]),
        _mac("NOdorants", P["n_odorants"]),
        _mac("MissingPct", f"{100 * P['missing_fraction']:.1f}\\%"),
        _mac("DoorCommit", P["door_commit"][:7]),
        _mac("PrimaryReal", f"{row['real']:.4f}"),
        _mac("PrimaryNullMean", f"{row['null_mean']:.4f}"),
        _mac("PrimaryNullSD", f"{row['null_sd']:.4f}"),
        _mac("PrimaryNullCV", f"{100 * row['null_cv']:.2f}\\%"),
        _mac("PrimaryNullSE", f"{row['null_se']:.5f}"),
        _mac("PrimaryRel", f"{pct(row['relative_difference'], 2)}\\%"),
        _mac("PrimaryZ", f"{row['z']:+.2f}"),
        _mac("PrimaryPtwo", pval(row["randomization"]["p_two_sided"])),
        _mac("PrimaryPlower", pval(row["randomization"]["p_lower"])),
        _mac("PrimaryRank", row["randomization"]["rank_from_top"]),
        _mac("BootLo", f"{pct(lo, 1)}\\%"), _mac("BootHi", f"{pct(hi, 1)}\\%"),
        _mac("EquivPrimary", "holds" if boot["equivalent"][f"{boot['primary_margin']:.3f}"]
             else "does not hold"),
        _mac("MarginPrimary", f"{100 * boot['primary_margin']:.0f}\\%"),
        _mac("MdeUp", f"{100 * pr['power']['mde80_upper']:.1f}\\%" if pr["power"]["mde80_upper"] else "n/a"),
        _mac("MdeDown", f"{100 * abs(pr['power']['mde80_lower']):.1f}\\%" if pr["power"]["mde80_lower"] else "n/a"),
        _mac("MinHolm", pval(min(r["randomization"]["p_two_sided_holm"]
                                 for r in pr["rows"] if not r["primary"]))),
        _mac("SecPMin", pval(min(r["randomization"]["p_two_sided"] for r in pr["rows"] if not r["primary"]))),
        _mac("SecPMax", pval(max(r["randomization"]["p_two_sided"] for r in pr["rows"] if not r["primary"]))),
        _mac("SecRelMin", f"{pct(min(r['relative_difference'] for r in pr['rows'] if not r['primary']), 1)}\\%"),
        _mac("SecRelMax", f"{pct(max(r['relative_difference'] for r in pr['rows'] if not r['primary']), 1)}\\%"),
        _mac("EquivTwoFive", "holds" if boot["equivalent"]["0.025"] else "does not hold"),
        _mac("NullsAbove", row["randomization"]["rank_from_top"] - 1),
        _mac("PrimaryPHolmAll", pval(_holm_all(pr))),
        _mac("TieConflictMax", f"{100 * max(r['tie_conflict_fraction'] for r in pr['rows']):.1f}\\%"),
    ]
    if cv:
        t = cv["real_q_test"]
        mac += [_mac("QRealP", pval(t["p_upper"])),
                _mac("QRealRel", f"{pct(cv['real_q'] / cv['pool_q_mean'] - 1, 1)}\\%"),
                _mac("PlateauSweeps", _plateau(cv)),
                _mac("JaccardPlateau", _jaccard_plateau(cv)[0]),
                _mac("JaccardFinal", f"{_jaccard_plateau(cv)[1]:.3f}")]
    if co:
        ts, old = co["two_stage"], co["superseded_group_bootstrap"]
        mac += [_mac("CovNew", f"{100 * ts['coverage']:.0f}\\%"),
                _mac("CovNewLo", f"{100 * ts['wilson95'][0]:.0f}"),
                _mac("CovNewHi", f"{100 * ts['wilson95'][1]:.0f}"),
                _mac("CovOld", f"{100 * old['coverage']:.0f}\\%"),
                _mac("CovOldLo", f"{100 * old['wilson95'][0]:.0f}"),
                _mac("CovOldHi", f"{100 * old['wilson95'][1]:.0f}"),
                _mac("CovDatasets", co["datasets"]), _mac("CovItems", co["n_items"])]
    if rb:
        rels, ps, n_sig = [], [], 0
        for c in rb["rows"]:
            pk = next(k for k in c["per_k"] if k["primary"])
            rels.append(pk["relative_difference"])
            ps.append(pk["p_two_sided"])
            n_sig += pk["p_two_sided"] < 0.05
        by = {c["id"]: next(k for k in c["per_k"] if k["primary"]) for c in rb["rows"]}
        imp = [by[i] for i in ("missing_glomerulus_mean", "missing_odour_mean", "missing_lowrank") if i in by]
        pmin_attainable = 2 / (rb["B"] + 1)
        mac += [_mac("RobNNeg", sum(r < 0 for r in rels)),
                _mac("RobNAtMin", sum(p <= pmin_attainable + 1e-12 for p in ps)),
                _mac("RobPFloor", pval(pmin_attainable))]
        if imp:
            mac += [_mac("ImputeRelMin", f"{pct(min(r['relative_difference'] for r in imp), 1)}\\%"),
                    _mac("ImputeRelMax", f"{pct(max(r['relative_difference'] for r in imp), 1)}\\%"),
                    _mac("ImputePMin", pval(min(r["p_two_sided"] for r in imp)))]
        mac += [_mac("RobN", len(rb["rows"])), _mac("RobB", rb["B"]),
                _mac("RobRelMin", f"{pct(min(rels), 1)}\\%"),
                _mac("RobRelMax", f"{pct(max(rels), 1)}\\%"),
                _mac("RobNSig", n_sig), _mac("RobMinP", pval(min(ps)))]
    if ar:
        m = ar["metrics"]["euclidean"]
        i = m["sizes"].index(pr["primary_k"])
        for key, name in (("k_bits", "Kbits"), ("storage_matched", "Storage"),
                          ("computation_matched", "Compute")):
            mac.append(_mac(f"Arch{name}Ratio", f"{m['gaussian'][key]['ratio_fly_over'][i]:.2f}"))
        mac.append(_mac("StorageBitsPrimary", ar["budgets"]["storage_matched"][str(pr["primary_k"])]))
        mac.append(_mac("ComputeBits", ar["budgets"]["computation_matched"][str(pr["primary_k"])]))

    # Table: wiring comparison
    wt = []
    for r in pr["rows"]:
        a = r["alternatives"]
        star = "$^\\ast$" if r["primary"] else ""
        wt.append(f"{r['k']}{star} & {r['real']:.4f} & {r['null_mean']:.4f} $\\pm$ {r['null_sd']:.4f} & "
                  f"{pct(r['relative_difference'], 1)} & {pval(r['randomization']['p_two_sided'])} & "
                  f"{'--' if r['primary'] else pval(r['randomization']['p_two_sided_holm'])} & "
                  f"{pct(a['shuffle_inputs']['relative_to_null'], 1)} & "
                  f"{pct(a['uniform_inputs_6']['relative_to_null'], 1)} & "
                  f"{pct(a['balanced_fanout']['relative_to_null'], 1)} \\\\")
    mac.append("\\newcommand{\\WiringRows}{" + "\n".join(wt) + "}")

    # Table: architecture
    if ar:
        m = ar["metrics"]["euclidean"]
        at = []
        for i, k in enumerate(m["sizes"]):
            g = m["gaussian"]
            at.append(f"{k} & {m['fly'][i]:.3f} & {g['k_bits']['mean'][i]:.3f} & "
                      f"{g['storage_matched']['mean'][i]:.3f} ({ar['budgets']['storage_matched'][str(k)]}) & "
                      f"{g['computation_matched']['mean'][i]:.3f} ({ar['budgets']['computation_matched'][str(k)]}) \\\\")
        mac.append("\\newcommand{\\ArchRows}{" + "\n".join(at) + "}")

    # Table: robustness summary by family
    if rb:
        fam = [("Baseline", ["baseline"]),
               ("Left hemisphere", ["hemisphere_L"]),
               ("$\\geq$5-synapse threshold", ["synapse_threshold_5"]),
               ("Missing data (3 imputations)", ["missing_glomerulus_mean", "missing_odour_mean", "missing_lowrank"]),
               ("Coverage thresholds (2)", ["coverage_strict", "coverage_loose"]),
               ("All 46 glomeruli with data, imputed", ["all_glomeruli"]),
               ("Mixture seeds (4)", ["mixture_seed_1", "mixture_seed_2", "mixture_seed_3", "mixture_seed_4"]),
               ("Mixture size 2 / 2--10", ["mixtures_pairs", "mixtures_wide"]),
               ("Measured odorants only", ["measured_only"]),
               ("Normalised / angular metric", ["metric_normalised", "metric_angular"]),
               ("Tie rules (index, include, 2 seeds)", ["ties_index", "ties_include", "tie_seed_1", "tie_seed_2"]),
               ("Synapse-weighted", ["weighted"]),
               ("Synthetic inputs (3)", ["synthetic_lowrank", "synthetic_gaussian", "synthetic_sparse"])]
        by = {c["id"]: c for c in rb["rows"]}
        rt = []
        for label, ids in fam:
            rows = [next(k for k in by[i]["per_k"] if k["primary"]) for i in ids if i in by]
            if not rows:
                continue
            rels = [r["relative_difference"] for r in rows]
            ps = [r["p_two_sided"] for r in rows]
            lo_r, hi_r = pct(min(rels), 1), pct(max(rels), 1)
            rel = lo_r if lo_r == hi_r else f"{lo_r} to {hi_r}"
            lo_p, hi_p = pval(min(ps)), pval(max(ps))
            p = lo_p if lo_p == hi_p else f"{lo_p}--{hi_p}"
            rt.append(f"{label} & {rel} & {p} \\\\")
        mac.append("\\newcommand{\\RobRows}{" + "\n".join(rt) + "}")
    mac += _benchmark_macros(_load("replication.json"), _load("connectome_benchmarks.json"))
    an = _load("connectomes.json")
    if an and an.get("hemispheres"):
        mac += animal_macros(an)
    return "\n".join(mac) + "\n"


_NAMES = {"sift": "SIFT", "glove": "GloVe", "mnist": "MNIST", "odours": "Odours"}
_IMAGE_WORD = ("sift", "glove", "mnist")


def _row_at(per: dict, k: int) -> dict:
    return next(r for r in per["ap"]["rows"] if r["k"] == k)


def _benchmark_macros(rp, cb) -> list[str]:
    """The 2017 protocol on four datasets: replication with random matrices
    (ReplRows), the connectome (ConnRows) and operation budgets
    (BudgetRows)."""
    mac = []
    if rp:
        ks = rp["protocol"]["hash_lengths"]
        i4 = ks.index(4)
        rows = []
        for name, r in rp["datasets"].items():
            for k in (4, 16):
                i = ks.index(k)
                f = {key: r[key]["ap"]["mean"][i] for key in ("lsh", "random_20k", "fly_20k", "fly_10d")}
                rc = {key: r[key]["recall"]["mean"][i] for key in ("lsh", "fly_10d")}
                rows.append(f"{_NAMES[name]} & {r['d']} & {k} & {f['lsh']:.3f} ({rc['lsh']:.2f}) & "
                            f"{f['random_20k']:.3f} & {f['fly_20k']:.3f} & "
                            f"{f['fly_10d']:.3f} ({rc['fly_10d']:.2f}) & "
                            f"{f['fly_10d'] / f['lsh']:.1f}$\\times$ \\\\")
        mac.append("\\newcommand{\\ReplRows}{" + "\n".join(rows) + "}")
        mn, sf, od = (rp["datasets"].get(n) for n in ("mnist", "sift", "odours"))
        if mn:
            lsh, fly = mn["lsh"]["ap"]["mean"][i4], mn["fly_10d"]["ap"]["mean"][i4]
            mac += [_mac("ReplMnistLsh", f"{lsh:.3f}"), _mac("ReplMnistFly", f"{fly:.3f}"),
                    _mac("ReplMnistRatio", f"{fly / lsh:.1f}"),
                    _mac("ReplOpsBitsMnist", mn["lsh_ops_10d_bits"])]
        if mn:
            tc = mn["truth_centred"]
            mac += [_mac("ReplMnistFlyRetr", f"{mn['fly_10d']['ap_retrieved']['mean'][i4]:.3f}"),
                    _mac("ReplMnistRatioCentred",
                         f"{tc['fly_10d']['ap']['mean'][i4] / tc['lsh']['ap']['mean'][i4]:.1f}"),
                    _mac("ReplMnistRecallRatio",
                         f"{mn['fly_10d']['recall']['mean'][i4] / mn['lsh']['recall']['mean'][i4]:.1f}"),
                    _mac("ReplMnistOverlapRatio",
                         f"{mn['fly_10d']['overlap']['mean'][i4] / mn['lsh']['overlap']['mean'][i4]:.1f}"),
                    _mac("ReplMnistLshRetr", f"{mn['lsh']['ap_retrieved']['mean'][i4]:.3f}"),
                    _mac("ReplMnistLshOverlap", f"{mn['lsh']['overlap']['mean'][i4]:.3f}")]
        if sf:
            mac += [_mac("ReplSiftRandom", f"{sf['random_20k']['ap']['mean'][i4]:.3f}"),
                    _mac("ReplSiftWta", f"{sf['fly_20k']['ap']['mean'][i4]:.3f}")]
        if od:
            lsh, fly = od["lsh"]["ap"]["mean"][i4], od["fly_10d"]["ap"]["mean"][i4]
            mac += [_mac("ReplOdourRatio", f"{fly / lsh:.1f}")]
        img = [rp["datasets"][n] for n in _IMAGE_WORD if n in rp["datasets"]]
        ops = [r["lsh_ops_10d"]["ap"]["mean"] for r in img]
        fly32 = [r["fly_10d"]["ap"]["mean"][ks.index(32)] for r in img]
        mac += [_mac("ReplTrials", rp["protocol"]["trials"]),
                _mac("ReplOpsMin", f"{min(ops):.2f}"), _mac("ReplOpsMax", f"{max(ops):.2f}"),
                _mac("ReplFlyMax", f"{max(fly32):.2f}")]
        # operation budgets: the 10d fly (10d cells x s additions) against k-projection LSH (2kd)
        bt = []
        for name, r in rp["datasets"].items():
            d, s = r["d"], r["sampled"]
            ratio = 10 * d * s / (2 * 4 * d)
            fly = r["fly_10d"]["ap"]["mean"][ks.index(32)]
            bt.append(f"{_NAMES[name]} & {d} & {ratio:.0f}$\\times$ & {r['lsh_ops_10d_bits']} & "
                      f"{r['lsh_ops_10d']['ap']['mean']:.3f} & {fly:.3f} \\\\")
        mac.append("\\newcommand{\\BudgetRows}{" + "\n".join(bt) + "}")
    if cb:
        rows = []
        for name, per in cb["datasets"].items():
            big = max(per["sizes"])
            for k in (4, 16, big):
                r = _row_at(per, k)
                rows.append(f"{_NAMES[name]} & {k} & {r['real']:.3f} & {r['null_mean']:.3f} & "
                            f"{pct(r['relative_difference'], 1)} & {pval(r['p_two_sided'])} & "
                            f"{r['random_2017']:.3f} & {r['lsh']:.3f} \\\\")
        mac.append("\\newcommand{\\ConnRows}{" + "\n".join(rows) + "}")
        allr = [r for per in cb["datasets"].values() for r in per["ap"]["rows"]]
        ref = next(cb["datasets"][n] for n in _IMAGE_WORD + ("odours",) if n in cb["datasets"])
        ops = [(per["ap"]["lsh_ops"], max(r["real"] for r in per["ap"]["rows"]))
               for per in cb["datasets"].values()]
        mac += [_mac("ConnB", cb["B"]), _mac("ConnTrials", cb["trials"]),
                _mac("ConnGlom", ref["n_glomeruli"]),
                _mac("ConnCells", f"{ref['n_cells']:,}".replace(",", "{,}")),
                _mac("ConnRelMin", f"{pct(min(r['relative_difference'] for r in allr), 1)}\\%"),
                _mac("ConnRelMax", f"{pct(max(r['relative_difference'] for r in allr), 1)}\\%"),
                _mac("ConnNSig", sum(r["p_two_sided"] < 0.05 for r in allr)),
                _mac("ConnNTests", len(allr)),
                _mac("ConnPFloor", pval(2 / (cb["B"] + 1))),
                _mac("ConnOpsBits", ref["lsh_ops_matched_bits"]),
                _mac("ConnOpsWins", sum(o > f for o, f in ops)), _mac("ConnNData", len(ops)),
                _mac("ConnRandGainMax", f"{100 * max(r['random_2017'] / r['real'] - 1 for r in allr):.0f}\\%")]
        if "mnist" in cb["datasets"]:
            r4 = _row_at(cb["datasets"]["mnist"], 4)
            mac += [_mac("ConnMnistReal", f"{r4['real']:.3f}"), _mac("ConnMnistLsh", f"{r4['lsh']:.3f}"),
                    _mac("ConnMnistRatio", f"{r4['real'] / r4['lsh']:.1f}")]
        if "odours" in cb["datasets"]:
            od = cb["datasets"]["odours"]
            r4 = _row_at(od, 4)
            big = _row_at(od, max(od["sizes"]))
            mac += [_mac("ConnOdourRatio", f"{r4['real'] / r4['lsh']:.1f}"),
                    _mac("ConnOdourRel", f"{pct(big['relative_difference'], 1)}\\%"),
                    _mac("ConnOdourP", pval(big["p_two_sided"])),
                    _mac("ConnOdourOpsBits", od["lsh_ops_matched_bits"]),
                    _mac("ConnOdourOps", f"{od['ap']['lsh_ops']:.3f}"),
                    _mac("ConnOdourFlyBig", f"{big['real']:.3f}"),
                    _mac("ConnOdourBigK", big["k"])]
    if rp and rp.get("dimension_sweep"):
        ds = rp["dimension_sweep"]
        rows = []
        for r in ds["rows"]:
            lsh, fly = r["lsh"]["ap"]["mean"][0], r["fly_10d"]["ap"]["mean"][0]
            best = max(r["fly_10d"]["ap"]["mean"])
            rows.append(f"{r['d']} & {10 * r['sampled'] / 8:.0f}$\\times$ & {lsh:.3f} & {fly:.3f} & "
                        f"{fly / lsh:.1f}$\\times$ & {r['lsh_ops_10d_bits']} & "
                        f"{r['lsh_ops_10d']['ap']['mean']:.3f} & {best:.3f} \\\\")
        mac.append("\\newcommand{\\DimRows}{" + "\n".join(rows) + "}")
    if cb:
        mac += _control_macros(cb)
    return mac


def _control_macros(cb: dict) -> list[str]:
    """Equal-connection controls and the centring ablation, relative to the
    null mean of the same run (ControlRows)."""
    rows = []
    for name, per in cb["datasets"].items():
        nc = per.get("no_centring")
        for k in (4, max(per["sizes"])):
            r = _row_at(per, k)
            rel = lambda key, rr=r: pct(rr[key] / rr["null_mean"] - 1, 1)
            cells = [pct(r["relative_difference"], 1), rel("in_equal"), rel("out_equal"),
                     rel("both_equal"), rel("random_2017")]
            if nc:
                r2 = _row_at(nc, k)
                cells += [pct(r2["relative_difference"], 1), pct(r2["both_equal"] / r2["null_mean"] - 1, 1)]
            rows.append(f"{_NAMES[name]} & {k} & " + " & ".join(cells) + " \\\\")
    both = [_row_at(per, k)["both_equal"] / _row_at(per, k)["null_mean"] - 1
            for per in cb["datasets"].values() for k in per["sizes"]]
    six = [_row_at(per, k)["random_2017"] / _row_at(per, k)["null_mean"] - 1
           for per in cb["datasets"].values() for k in per["sizes"]]
    img = [per for n, per in cb["datasets"].items() if n != "odours"]
    rel = lambda key: [_row_at(per, k)[key] / _row_at(per, k)["null_mean"] - 1
                       for per in img for k in per["sizes"]]
    conn = [_row_at(per, k)["relative_difference"] for per in img for k in per["sizes"]]
    return ["\\newcommand{\\ControlRows}{" + "\n".join(rows) + "}",
            _mac("CtrlOutMin", f"{pct(min(rel('out_equal')), 0)}\\%"),
            _mac("CtrlOutMax", f"{pct(max(rel('out_equal')), 0)}\\%"),
            _mac("CtrlInMin", f"{pct(min(rel('in_equal')), 0)}\\%"),
            _mac("CtrlInMax", f"{pct(max(rel('in_equal')), 0)}\\%"),
            _mac("ConnImgMin", f"{pct(min(conn), 1)}\\%"), _mac("ConnImgMax", f"{pct(max(conn), 1)}\\%"),
            _mac("CtrlBothMin", f"{pct(min(both), 1)}\\%"), _mac("CtrlBothMax", f"{pct(max(both), 1)}\\%"),
            _mac("CtrlSixMin", f"{pct(min(six), 1)}\\%"), _mac("CtrlSixMax", f"{pct(max(six), 1)}\\%")]


def benchmark_figure(cb: dict, path: Path) -> None:
    """One panel per dataset, all methods on the same input: connectome,
    null mean with a 2 SD band, the 2017 construction, LSH with k projections,
    and LSH with the operation count of the measured projection."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    names = [n for n in ("sift", "glove", "mnist", "odours") if n in cb["datasets"]]
    fig, axes = plt.subplots(1, len(names), figsize=(9.0, 2.6), sharey=True)
    axes = np.atleast_1d(axes)
    for ax, name in zip(axes, names):
        per = cb["datasets"][name]
        rows = per["ap"]["rows"]
        ks = [r["k"] for r in rows]
        nm = np.array([r["null_mean"] for r in rows])
        nsd = np.array([r["null_sd"] for r in rows])
        ax.fill_between(ks, nm - 2 * nsd, nm + 2 * nsd, color=_ORANGE, alpha=0.25, lw=0)
        ax.plot(ks, nm, color=_ORANGE, lw=1.2, label="null mean $\\pm$2 SD")
        ax.plot(ks, [r["real"] for r in rows], "-o", color=_BLUE, lw=1.8, ms=3.5,
                markeredgecolor=_SURFACE, markeredgewidth=0.6, label="connectome")
        ax.plot(ks, [r["random_2017"] for r in rows], "--", color=_BLUE, lw=1.2,
                label="2017 construction (6 inputs)")
        ax.plot(ks, [r["both_equal"] for r in rows], ":", color=_BLUE, lw=1.4,
                label="even degrees, same connections")
        ax.plot(ks, [r["lsh"] for r in rows], "-s", color=_VIOLET, lw=1.5, ms=3.2,
                markeredgecolor=_SURFACE, markeredgewidth=0.6, label="LSH, k projections")
        ax.axhline(per["ap"]["lsh_ops"], color=_VIOLET, ls=":", lw=1.4,
                   label="LSH, equal operations")
        ax.set_xscale("log", base=2)
        ax.set_xticks(ks)
        ax.set_xticklabels(ks, fontsize=7)
        ax.set_title(f"{_NAMES[name]} (d = {per['n_glomeruli']})", color=_INK, fontsize=9, loc="left")
        ax.set_xlabel("active Kenyon cells k", fontsize=8)
        ax.grid(axis="y", color="#ecebe6", lw=0.7)
        ax.set_axisbelow(True)
    axes[0].set_ylabel("mean average precision")
    h, lab = axes[0].get_legend_handles_labels()
    leg = fig.legend(h, lab, loc="lower center", ncol=6, frameon=False, fontsize=6.5,
                     bbox_to_anchor=(0.5, -0.06))
    for t in leg.get_texts():
        t.set_color(_MUTED)
    fig.tight_layout(rect=(0, 0.06, 1, 1))
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def _benchmark_supplement(rp, cb) -> list[str]:
    L = []
    if rp:
        pc = rp["protocol"]
        L += ["## The 2017 protocol with random matrices", "",
              f"{pc['n']} vectors per dataset, {pc['queries']} queries, top {100 * pc['top']:.0f}% "
              f"neighbours, {pc['trials']} trials; each Kenyon cell samples {100 * pc['sampling']:.0f}% "
              "of the inputs. Mean (SD over trials). Reported in the 2017 paper: MNIST k=4 LSH 0.160, "
              "fly (m=10d) 0.448; SIFT k=4 random selection 0.177, WTA (m=20k) 0.324. "
              "Odours (DoOR mixtures) were not part of the 2017 benchmarks.", ""]
        for met, title in (("ap", "AP@200 (average precision, all 200 true neighbours in the denominator)"),
                           ("recall", "recall@200"),
                           ("overlap", "list overlap (FlyLSH reference code; not AP)"),
                           ("ap_retrieved", "precision averaged over retrieved neighbours only "
                                            "(the flawed score of revision 3; not AP)")):
            L += [f"### {title}", "",
                  "| dataset | k | LSH | sign LSH | random 20k | fly 20k | fly 10d |",
                  "|---|---|---|---|---|---|---|"]
            for name, r in rp["datasets"].items():
                for i, k in enumerate(pc["hash_lengths"]):
                    c = {key: f"{r[key][met]['mean'][i]:.3f} ({r[key][met]['sd'][i]:.3f})"
                         for key in ("lsh", "lsh_sign", "random_20k", "fly_20k", "fly_10d")}
                    L.append(f"| {_NAMES[name]} | {k} | {c['lsh']} | {c['lsh_sign']} | "
                             f"{c['random_20k']} | {c['fly_20k']} | {c['fly_10d']} |")
            L += ["", "LSH given the operation count of the m = 10d fly (10d cells x s additions, "
                      "2d operations per projection):", ""]
            for name, r in rp["datasets"].items():
                L.append(f"- {_NAMES[name]}: {r['lsh_ops_10d_bits']} projections, "
                         f"{r['lsh_ops_10d'][met]['mean']:.3f} ({r['lsh_ops_10d'][met]['sd']:.3f})")
            L.append("")
    if cb:
        L += ["## The connectome under the 2017 protocol", "",
              f"{cb['trials']} trials, {cb['B']} curveball nulls, each matrix's score averaged over "
              "trials. SIFT, GloVe and MNIST are reduced by PCA to one component per glomerulus "
              "and assigned to glomeruli at random in each trial; odours use the measured glomeruli. "
              "'2017 random': every cell samples 6 glomeruli uniformly.", ""]
        for met in ("ap", "recall", "overlap"):
            L += [f"### {met}", "",
                  "| dataset | k | measured | null mean +/- SD | rel. diff. | p | 2017 random | LSH | sign LSH |",
                  "|---|---|---|---|---|---|---|---|---|"]
            for name, per in cb["datasets"].items():
                for r in per[met]["rows"]:
                    L.append(f"| {_NAMES[name]} | {r['k']} | {r['real']:.4f} | {r['null_mean']:.4f} +/- "
                             f"{r['null_sd']:.4f} | {pct(r['relative_difference'], 2)}% | "
                             f"{pval(r['p_two_sided'])} | {r['random_2017']:.4f} | {r['lsh']:.4f} | "
                             f"{r['lsh_sign']:.4f} |")
                L.append(f"| {_NAMES[name]} (d = {per['n_glomeruli']}, m = {per['n_cells']}) | "
                         f"LSH, equal operations ({per['lsh_ops_matched_bits']} projections) | "
                         f"{per[met]['lsh_ops']:.4f} | | | | | | |")
            L.append("")
    return L


# ------------------------------------------------------------------ connectomes

def _hemi_stats(h: dict) -> dict:
    prim = next(r for r in h["odours"] if r["primary"])
    matched = next(r for r in h["odours_matched"] if r["primary"])
    proto = [r for per in h["protocol"].values() for r in per["ap"]["rows"]]
    mn4 = next(r for r in h["protocol"]["mnist"]["ap"]["rows"] if r["k"] == 4)
    return {"prim": prim, "matched": matched, "proto": proto,
            "mnist_ratio": mn4["real"] / mn4["lsh"],
            "proto_min": min(r["relative_difference"] for r in proto),
            "proto_max": max(r["relative_difference"] for r in proto),
            "proto_mean": float(np.mean([r["relative_difference"] for r in proto])),
            "both_mean": float(np.mean([r["both_equal"] / r["null_mean"] - 1 for r in proto])),
            "six_mean": float(np.mean([r["random_2017"] / r["null_mean"] - 1 for r in proto]))}


def animal_macros(an: dict) -> list[str]:
    hs = an["hemispheres"]
    rows = []
    for key, h in hs.items():
        s = _hemi_stats(h)
        f = h["full"]
        rows.append(f"{h['label']} & {h['sex'][0]} & {f['n_cells']:,} & {f['inputs_mean']:.2f} & "
                    f"{f['fan_out_cv']:.2f} & {h['structure']['z']:+.1f} & "
                    f"{pct(s['prim']['relative_difference'], 1)} ({pval(s['prim']['p_two_sided'])}) & "
                    f"{pct(s['matched']['relative_difference'], 1)} ({pval(s['matched']['p_two_sided'])}) & "
                    f"{pct(s['proto_min'], 1)} to {pct(s['proto_max'], 1)} & "
                    f"{pct(s['both_mean'], 1)} & {pct(s['six_mean'], 1)} & "
                    f"{s['mnist_ratio']:.1f} \\\\".replace(",", "{,}"))
    st = {k: _hemi_stats(h) for k, h in hs.items()}
    allproto = [r for s in st.values() for r in s["proto"]]
    odour = [s["prim"] for s in st.values()]
    matched = [s["matched"] for s in st.values()]
    zs = [h["structure"]["z"] for h in hs.values()]
    # hemispheres of one animal are not independent: summarise per animal
    animals = {}
    for k, h in hs.items():
        animals.setdefault(h["dataset"], []).append(st[k])
    an_odour = {a: np.mean([s["prim"]["relative_difference"] for s in v]) for a, v in animals.items()}
    an_proto = {a: np.mean([s["proto_mean"] for s in v]) for a, v in animals.items()}
    pfloor = 2 / (an["B_bench"] + 1)
    return ["\\newcommand{\\AnimalRows}{" + "\n".join(rows) + "}",
            _mac("AnimN", len(hs)), _mac("AnimAnimals", len(animals)),
            _mac("AnimB", an["B"]), _mac("AnimBBench", an["B_bench"]),
            _mac("AnimTrials", an["trials"]), _mac("AnimPFloor", pval(pfloor)),
            _mac("AnimOdourPFloor", pval(2 / (an["B"] + 1))),
            _mac("AnimCommon", len(an["common_glomeruli"])),
            _mac("AnimCommonOdour", len(an["common_odour_glomeruli"])),
            _mac("AnimRelMin", f"{pct(min(r['relative_difference'] for r in allproto), 1)}\\%"),
            _mac("AnimRelMax", f"{pct(max(r['relative_difference'] for r in allproto), 1)}\\%"),
            _mac("AnimNNeg", sum(r["relative_difference"] < 0 for r in allproto)),
            _mac("AnimRelMedian", f"{pct(float(np.median([r['relative_difference'] for r in allproto])), 1)}\\%"),
            _mac("AnimRelIQR", "{} to {}".format(*(f"{pct(v, 1)}\\%" for v in np.percentile(
                [r["relative_difference"] for r in allproto], [25, 75])))),
            _mac("AnimNProto", len(allproto)),
            _mac("AnimNFloor", sum(r["p_two_sided"] <= pfloor + 1e-12 and r["relative_difference"] < 0
                                   for r in allproto)),
            _mac("AnimNFloorUp", sum(r["p_two_sided"] <= pfloor + 1e-12 and r["relative_difference"] > 0
                                     for r in allproto)),
            _mac("AnimOdourMin", f"{pct(min(r['relative_difference'] for r in odour), 1)}\\%"),
            _mac("AnimOdourMax", f"{pct(max(r['relative_difference'] for r in odour), 1)}\\%"),
            _mac("AnimOdourNNeg", sum(r["relative_difference"] < 0 for r in odour)),
            _mac("AnimOdourNSig", sum(r["p_two_sided"] < 0.05 for r in odour)),
            _mac("AnimMatchedMin", f"{pct(min(r['relative_difference'] for r in matched), 1)}\\%"),
            _mac("AnimMatchedMax", f"{pct(max(r['relative_difference'] for r in matched), 1)}\\%"),
            _mac("AnimMatchedNSig", sum(r["p_two_sided"] < 0.05 for r in matched)),
            _mac("AnimalsOdourNeg", sum(v < 0 for v in an_odour.values())),
            _mac("AnimalsProtoNeg", sum(v < 0 for v in an_proto.values())),
            _mac("AnimQzMin", f"{min(zs):.1f}"), _mac("AnimQzMax", f"{max(zs):.1f}"),
            _mac("AnimQNSig", sum(h["structure"]["test"]["p_upper"] < 0.05 for h in hs.values())),
            _mac("AnimBothMin", f"{pct(min(s['both_mean'] for s in st.values()), 1)}\\%"),
            _mac("AnimBothMax", f"{pct(max(s['both_mean'] for s in st.values()), 1)}\\%"),
            _mac("AnimLshMin", f"{min(s['mnist_ratio'] for s in st.values()):.1f}"),
            _mac("AnimLshMax", f"{max(s['mnist_ratio'] for s in st.values()):.1f}"),
            _mac("AnimCellsMin", f"{min(h['full']['n_cells'] for h in hs.values()):,}".replace(",", "{,}")),
            _mac("AnimCellsMax", f"{max(h['full']['n_cells'] for h in hs.values()):,}".replace(",", "{,}")),
            _mac("AnimInMin", f"{min(h['full']['inputs_mean'] for h in hs.values()):.2f}"),
            _mac("AnimInMax", f"{max(h['full']['inputs_mean'] for h in hs.values()):.2f}")]


def animal_figure(an: dict, path: Path) -> None:
    """Left: inputs per Kenyon cell in every hemisphere. Right: every
    hemisphere's relative difference to its null, per dataset and hash size
    under the 2017 protocol, and at the primary size of the odour analysis."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    hs = list(an["hemispheres"].values())
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.0, 2.9), gridspec_kw={"width_ratios": [1, 1.7]})
    shades = {"malecns": _BLUE, "hemibrain": _ORANGE, "flywire": _VIOLET, "banc": "#1b9e77"}
    for h in hs:
        hist = np.array(h["full"]["inputs_hist"], float)
        a1.plot(np.arange(len(hist)), hist / hist.sum(), color=shades[h["dataset"]], lw=1.3,
                ls="-" if h["side"] == "R" else "--", label=h["label"])
    a1.set_xlim(0, 14)
    a1.set_xlabel("glomerular inputs per Kenyon cell")
    a1.set_ylabel("fraction of cells")
    a1.set_title("Degree sequences", color=_INK, fontsize=9.5, loc="left")
    leg = a1.legend(frameon=False, fontsize=6.5, ncol=1)
    for t in leg.get_texts():
        t.set_color(_MUTED)
    marks = {"sift": "o", "glove": "s", "mnist": "^", "odours": "D"}
    rng = np.random.default_rng(0)
    for i, h in enumerate(hs):
        for name, per in h["protocol"].items():
            v = [100 * r["relative_difference"] for r in per["ap"]["rows"]]
            a2.scatter(i + rng.uniform(-0.25, 0.25, len(v)), v, s=9, marker=marks[name],
                       color=shades[h["dataset"]], alpha=0.55, linewidths=0,
                       label=name if i == 0 else None)
        prim = next(r for r in h["odours"] if r["primary"])
        a2.scatter([i], [100 * prim["relative_difference"]], s=60, marker="*", color=_INK,
                   zorder=3, label="odour analysis, primary k" if i == 0 else None)
    a2.axhline(0, color="#9a9992", lw=0.9)
    a2.set_xticks(range(len(hs)))
    a2.set_xticklabels([h["label"] for h in hs], fontsize=7, rotation=20)
    a2.set_ylabel("mAP relative to null mean (%)")
    a2.set_title("Connectome against its own null", color=_INK, fontsize=9.5, loc="left")
    a2.grid(axis="y", color="#ecebe6", lw=0.7)
    a2.set_axisbelow(True)
    leg = a2.legend(frameon=False, fontsize=6.5, ncol=5, loc="lower center",
                    bbox_to_anchor=(0.5, -0.42))
    for t in leg.get_texts():
        t.set_color(_MUTED)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def animal_supplement(an: dict) -> list[str]:
    L = ["## Four connectomes, seven hemispheres", "",
         f"Identical settings for every hemisphere: pairing structure and odour analysis against "
         f"{an['B']} curveball nulls; the 2017 protocol against {an['B_bench']} nulls over "
         f"{an['trials']} trials.", "",
         "| hemisphere | sex | glomeruli | Kenyon cells | PNs | inputs/cell (mean, median) | fan-out CV | "
         "synapses | Q z | odour glomeruli |", "|---|---|---|---|---|---|---|---|---|---|"]
    for h in an["hemispheres"].values():
        f = h["full"]
        L.append(f"| {h['label']} | {h['sex']} | {f['n_glomeruli']} | {f['n_cells']} | {f['n_pn']} | "
                 f"{f['inputs_mean']:.2f}, {f['inputs_median']:.0f} | {f['fan_out_cv']:.2f} | "
                 f"{f['synapses']:.0f} | {h['structure']['z']:+.1f} | {len(h['odour_glomeruli'])} |")
    for key, title in (("odours", "each connectome's DoOR glomeruli"),
                       ("odours_matched", f"the {len(an['common_odour_glomeruli'])} DoOR glomeruli "
                                          "every hemisphere has")):
        L += ["", f"### Odour analysis (4000 mixtures, kappa = 10), {title}", "",
              "| hemisphere | k | measured | null mean +/- SD | rel. diff. | p | fan-in equal | "
              "fan-out equal | both equal | six inputs |", "|---|---|---|---|---|---|---|---|---|---|"]
        for h in an["hemispheres"].values():
            for r in h[key]:
                L.append(f"| {h['label']} | {r['k']}{'*' if r['primary'] else ''} | {r['real']:.4f} | "
                         f"{r['null_mean']:.4f} +/- {r['null_sd']:.4f} | {pct(r['relative_difference'], 2)}% | "
                         f"{pval(r['p_two_sided'])} | {pct(r['in_equal_relative'], 1)}% | "
                         f"{pct(r['out_equal_relative'], 1)}% | {pct(r['both_equal_relative'], 1)}% | "
                         f"{pct(r['uniform6_relative'], 1)}% |")
    L += ["", "### The 2017 protocol (mAP)", "",
          "| hemisphere | dataset | k | measured | null mean | rel. diff. | p | even degrees | "
          "six inputs | LSH |", "|---|---|---|---|---|---|---|---|---|---|"]
    for h in an["hemispheres"].values():
        for name, per in h["protocol"].items():
            for r in per["ap"]["rows"]:
                L.append(f"| {h['label']} | {_NAMES[name]} | {r['k']} | {r['real']:.4f} | "
                         f"{r['null_mean']:.4f} | {pct(r['relative_difference'], 2)}% | "
                         f"{pval(r['p_two_sided'])} | {r['both_equal']:.4f} | {r['random_2017']:.4f} | "
                         f"{r['lsh']:.4f} |")
    L.append("")
    return L


def _plateau(cv: dict, tol_sd: float = 3.0) -> str:
    """First checkpoint from which every chain's co-occurrence statistic stays
    inside `tol_sd` standard deviations of the null distribution (200
    independent draws). Single stationary draws fall outside one SD about a
    third of the time, so a one-SD criterion is never met; three is the
    appropriate envelope for individual values."""
    mu, sd = cv["pool_q_mean"], cv["pool_q_sd"]
    marks = cv["marks"]
    for j, mk in enumerate(marks):
        if all(abs(ch[i]["cooccurrence_q"] - mu) <= tol_sd * sd
               for ch in cv["chains"] for i in range(j, len(marks))):
            return f"{mk:g}"
    return "n/a"


def _jaccard_plateau(cv: dict, tol: float = 0.005) -> tuple[str, float]:
    """First checkpoint from which the mean Jaccard overlap with the measured
    matrix stays within `tol` of its value at the last checkpoint."""
    marks = cv["marks"]
    mean = [np.mean([ch[j]["jaccard_to_real"] for ch in cv["chains"]]) for j in range(len(marks))]
    final = mean[-1]
    for j, mk in enumerate(marks):
        if all(abs(v - final) <= tol for v in mean[j:]):
            return f"{mk:g}", float(final)
    return "n/a", float(final)


# ------------------------------------------------------------------ supplement


def supplement(pr, ar, cv, rb, co) -> str:
    L = ["# Supplement: full results", "",
         "Generated by `python -m flypath report` from `results/*.json`. Every table in the",
         "paper is a subset of what is here.", ""]
    if rb:
        L += [f"## Robustness grid ({rb['B']} curveball nulls per condition)", "",
              "Relative mAP difference (connectome vs null mean) and two-sided randomization p,",
              "for the primary hash size (5% of Kenyon cells) and every secondary size.", ""]
        ks = sorted({k["k"] for c in rb["rows"] for k in c["per_k"] if not k["primary"]})
        L.append("| condition | items | glom. | cells | primary k: rel. diff | p | "
                 + " | ".join(f"k={k}: rel / p" for k in ks) + " |")
        L.append("|---|---|---|---|---|---|" + "---|" * len(ks))
        for c in rb["rows"]:
            pk = next(k for k in c["per_k"] if k["primary"])
            sec = {k["k"]: k for k in c["per_k"] if not k["primary"]}
            L.append(f"| {c['label']} | {c['n_items']} | {c['n_glomeruli']} | {c['n_cells']} | "
                     f"{pct(pk['relative_difference'], 2)}% (k={pk['k']}) | {pval(pk['p_two_sided'])} | "
                     + " | ".join(f"{pct(sec[k]['relative_difference'], 1)}% / {pval(sec[k]['p_two_sided'])}"
                                  if k in sec else "" for k in ks) + " |")
        L.append("")
    if pr:
        L += ["## Power of the randomization test (primary hash size)", "",
              "Shift model: the connectome behaves like a random wiring whose score is",
              "multiplied by (1 + delta); rejection rate at alpha = 0.05 against the empirical null.", "",
              "| delta | power (one-sided) |", "|---|---|"]
        for d, v in {**pr["power"]["lower"], **pr["power"]["upper"]}.items():
            L.append(f"| {pct(float(d), 1)}% | {v:.2f} |")
        L += ["", f"80% power reached at {pct(pr['power']['mde80_lower'] or 0, 1)}% (worse) and "
                  f"{pct(pr['power']['mde80_upper'] or 0, 1)}% (better).", ""]
        b = pr["bootstrap"]
        L += ["## Equivalence", "",
              f"Two-stage bootstrap ({b['draws']} replicates) 90% interval for the relative difference: "
              f"[{pct(b['relative_ci'][0], 2)}%, {pct(b['relative_ci'][1], 2)}%].", "",
              "| margin | equivalent (TOST, alpha = 0.05 per side) |", "|---|---|"]
        for mg, ok in b["equivalent"].items():
            L.append(f"| +/-{100 * float(mg):.1f}% | {'yes' if ok else 'no'} |")
        L.append("")
    if co:
        L += ["## Coverage of the interval procedures", "",
              f"{co['datasets']} datasets drawn from a rank-6 generative model fitted to the source "
              f"profiles; {co['n_items']} items each; k = {co['k']}; nominal 90%.", "",
              "| procedure | coverage | Wilson 95% | median width |", "|---|---|---|---|"]
        for key, name in (("two_stage", "two-stage bootstrap (this revision)"),
                          ("superseded_group_bootstrap", "group bootstrap (previous revision)")):
            c = co[key]
            L.append(f"| {name} | {100 * c['coverage']:.0f}% | {100 * c['wilson95'][0]:.0f}-"
                     f"{100 * c['wilson95'][1]:.0f}% | {100 * c['median_width']:.2f} pp |")
        L.append("")
    if cv:
        L += ["## Curveball mixing", "",
              "Glomerulus co-occurrence statistic Q and Jaccard overlap with the measured matrix, "
              "per chain and checkpoint.", "",
              f"Reference (200 pool nulls at 30 sweeps): Q = {cv['pool_q_mean']:.0f} +/- {cv['pool_q_sd']:.0f}; "
              f"measured matrix Q = {cv['real_q']:.0f} (upper-tail p = {pval(cv['real_q_test']['p_upper'])}).", "",
              "| sweeps | " + " | ".join(f"chain {i + 1} Q" for i in range(len(cv["chains"]))) + " | mean Jaccard |",
              "|---|" + "---|" * (len(cv["chains"]) + 1)]
        for j, mk in enumerate(cv["marks"]):
            qs = [ch[j]["cooccurrence_q"] for ch in cv["chains"]]
            jac = np.mean([ch[j]["jaccard_to_real"] for ch in cv["chains"]])
            L.append(f"| {mk:g} | " + " | ".join(f"{q:.0f}" for q in qs) + f" | {jac:.3f} |")
        L += ["", "mAP at the primary hash size along the chains:", "",
              "| sweeps | " + " | ".join(f"chain {i + 1}" for i in range(len(cv["chains"]))) + " |",
              "|---|" + "---|" * len(cv["chains"])]
        for j, mk in enumerate(cv["marks"]):
            vals = [ch[j]["map"] for ch in cv["chains"]]
            if all(v is not None for v in vals):
                L.append(f"| {mk:g} | " + " | ".join(f"{v:.4f}" for v in vals) + " |")
        L.append("")
    if ar:
        L += ["## Architecture comparison under all three ground truths", ""]
        for metric, m in ar["metrics"].items():
            L += [f"### {metric}", "", "| k | fly | Gaussian k bits | storage-matched | computation-matched |",
                  "|---|---|---|---|---|"]
            for i, k in enumerate(m["sizes"]):
                g = m["gaussian"]
                L.append(f"| {k} | {m['fly'][i]:.4f} | {g['k_bits']['mean'][i]:.4f} "
                         f"({g['k_bits']['ratio_fly_over'][i]:.2f}x) | "
                         f"{g['storage_matched']['mean'][i]:.4f} ({g['storage_matched']['ratio_fly_over'][i]:.2f}x) | "
                         f"{g['computation_matched']['mean'][i]:.4f} ({g['computation_matched']['ratio_fly_over'][i]:.2f}x) |")
            L.append("")
        L += [f"Budgets (bits): k-bit = k; storage-matched = ceil(log2 C(m, k)); computation-matched = "
              f"round(nnz / 2d) = {ar['budgets']['computation_matched'][str(pr['primary_k'])]}, "
              f"counting operations as Dasgupta et al. (2017) do (d multiplications plus d additions "
              f"per Gaussian projection, one addition per non-zero of M). "
              f"Ratios are fly / Gaussian.", ""]
    L += _benchmark_supplement(_load("replication.json"), _load("connectome_benchmarks.json"))
    an = _load("connectomes.json")
    if an and an.get("hemispheres"):
        L += animal_supplement(an)
    return "\n".join(L)


# ------------------------------------------------------------------ README block

def readme_block(pr, ar, rb, co) -> str:
    row = _primary_row(pr)
    b = pr["bootstrap"]
    m = ar["metrics"]["euclidean"] if ar else None
    L = ["<!-- results:start (generated by `python -m flypath report`; do not edit) -->", "",
         f"Primary hash size k = {pr['primary_k']} (5% of {pr['projection']['n_cells']} Kenyon cells), "
         f"{pr['n_items']} synthetic mixtures, {pr['B']} curveball nulls:", "",
         "| k | measured | null mean +/- SD | rel. diff. | p (two-sided) | p (Holm) |",
         "|---|---|---|---|---|---|"]
    for r in pr["rows"]:
        holm = "(primary, not adjusted)" if r["primary"] else pval(r["randomization"]["p_two_sided_holm"])
        L.append(f"| {r['k']}{' (primary)' if r['primary'] else ''} | {r['real']:.4f} | "
                 f"{r['null_mean']:.4f} +/- {r['null_sd']:.4f} | {pct(r['relative_difference'], 2)}% | "
                 f"{pval(r['randomization']['p_two_sided'])} | {holm} |")
    equiv = b["equivalent"][f"{b['primary_margin']:.3f}"]
    L += ["", f"Two-stage bootstrap 90% interval for the relative difference at the primary size: "
              f"[{pct(b['relative_ci'][0], 1)}%, {pct(b['relative_ci'][1], 1)}%]; "
              f"equivalence at the pre-specified +/-{100 * b['primary_margin']:.0f}% margin: "
              f"{'yes' if equiv else 'no'}."]
    if m:
        i = m["sizes"].index(pr["primary_k"])
        g = m["gaussian"]
        L += ["", f"Fly hash / Gaussian sign code at k = {pr['primary_k']}: "
                  f"{g['k_bits']['ratio_fly_over'][i]:.2f}x at k bits, "
                  f"{g['storage_matched']['ratio_fly_over'][i]:.2f}x at matched storage "
                  f"({ar['budgets']['storage_matched'][str(pr['primary_k'])]} bits), "
                  f"{g['computation_matched']['ratio_fly_over'][i]:.2f}x at matched operations "
                  f"({ar['budgets']['computation_matched'][str(pr['primary_k'])]} bits)."]
    rp, cb = _load("replication.json"), _load("connectome_benchmarks.json")
    if rp and "mnist" in rp["datasets"]:
        mn = rp["datasets"]["mnist"]
        i4 = rp["protocol"]["hash_lengths"].index(4)
        L += ["", f"2017 protocol with random matrices, MNIST, k = 4: LSH {mn['lsh']['ap']['mean'][i4]:.3f} "
                  f"(reported 0.160), fly hash {mn['fly_10d']['ap']['mean'][i4]:.3f} (reported 0.448)."]
    if cb:
        allr = [r for per in cb["datasets"].values() for r in per["ap"]["rows"]]
        L += ["", f"Connectome under the 2017 protocol (SIFT, GloVe, MNIST via PCA; odours): "
                  f"{pct(min(r['relative_difference'] for r in allr), 1)}% to "
                  f"{pct(max(r['relative_difference'] for r in allr), 1)}% relative to "
                  f"{cb['B']} curveball nulls across {len(allr)} dataset-size combinations."]
    if co:
        L += ["", f"Coverage of the 90% interval in simulation: "
                  f"{100 * co['two_stage']['coverage']:.0f}% (previous procedure: "
                  f"{100 * co['superseded_group_bootstrap']['coverage']:.0f}%)."]
    if rb:
        L += ["", f"Robustness: {len(rb['rows'])} one-factor variations, see "
                  f"[results/SUPPLEMENT.md](results/SUPPLEMENT.md)."]
    L += ["", "<!-- results:end -->"]
    return "\n".join(L)


# ------------------------------------------------------------------ checksums

def verify_checksums(cfg) -> bool:
    from .flyhash import sha256
    ok = True
    for line in (ROOT / "DATA_CHECKSUMS.txt").read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        h, name = line.split(None, 1)
        f = cfg.raw_dir / name
        got = sha256(f) if f.exists() else "missing"
        match = got == h
        ok &= match
        print(f"{'ok  ' if match else 'FAIL'}  {name}")
    return ok


# ------------------------------------------------------------------ all

def build_all() -> None:
    pr, ar = _load("primary.json"), _load("architecture.json")
    cv, rb, co = _load("convergence.json"), _load("robustness.json"), _load("coverage.json")
    if not pr:
        raise SystemExit("results/primary.json missing; run: python -m flypath analyse")
    figure(pr, ar, RES / "flyhash.png")
    cb = _load("connectome_benchmarks.json")
    if cb:
        benchmark_figure(cb, RES / "benchmarks.png")
    an = _load("connectomes.json")
    if an and an.get("hemispheres"):
        animal_figure(an, RES / "connectomes.png")
    (ROOT / "paper" / "generated.tex").write_text(latex(pr, ar, cv, rb, co))
    (RES / "SUPPLEMENT.md").write_text(supplement(pr, ar, cv, rb, co))
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- results:start", "<!-- results:end -->"
    if start in text and end in text:
        a = text.index(start)
        b = text.index(end) + len(end)
        readme.write_text(text[:a] + readme_block(pr, ar, rb, co) + text[b:])
    print("wrote results/flyhash.png, paper/generated.tex, results/SUPPLEMENT.md, README block")
