"""Regenerate every reported number from results/*.json.

Writes
  results/flyhash.png        the figure
  paper/generated.tex        LaTeX macros and table bodies used by the paper
  results/SUPPLEMENT.md      full robustness grid, power, coverage, mixing
  README.md                  the block between the results markers

so the manuscript, the figure, the supplement and the README cannot drift apart.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .config import ROOT

RES = ROOT / "results"


def _load(name: str) -> dict | None:
    f = RES / name
    return json.loads(f.read_text()) if f.exists() else None


def pct(x: float, d: int = 1) -> str:
    return f"{100 * x:+.{d}f}"


def pval(p: float) -> str:
    return f"{p:.3f}"


def _primary_row(pr: dict) -> dict:
    return next(r for r in pr["rows"] if r["primary"])


# ------------------------------------------------------------------ figure

_BLUE, _ORANGE, _VIOLET = "#2a78d6", "#eb6834", "#4a3aa7"   # validated CVD-safe
_INK, _MUTED, _SURFACE = "#0b0b0b", "#52514e", "#ffffff"


def figure(pr: dict, ar: dict, path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "figure.dpi": 220, "font.size": 9, "axes.labelsize": 9,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.edgecolor": "#b8b7b1", "axes.labelcolor": _MUTED,
        "xtick.color": _MUTED, "ytick.color": _MUTED,
        "figure.facecolor": _SURFACE, "axes.facecolor": _SURFACE})
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.0, 3.1))

    m = ar["metrics"]["euclidean"]
    ks = m["sizes"]
    g = m["gaussian"]
    lines = [("fly hash (measured wiring)", m["fly"], _BLUE, "-", "o"),
             ("Gaussian, k bits", g["k_bits"]["mean"], _VIOLET, "-", "s"),
             ("Gaussian, storage-matched", g["storage_matched"]["mean"], _VIOLET, "--", "^"),
             ("Gaussian, operation-matched", g["computation_matched"]["mean"], _VIOLET, ":", "v")]
    for label, y, c, ls, mk in lines:
        a1.plot(ks, y, ls, color=c, lw=1.8, marker=mk, ms=4.5,
                markeredgecolor=_SURFACE, markeredgewidth=0.8, label=label)
    leg = a1.legend(loc="lower right", frameon=False, fontsize=7, handlelength=2.2)
    for t in leg.get_texts():
        t.set_color(_MUTED)
    a1.set_xscale("log", base=2)
    a1.set_xticks(ks)
    a1.set_xticklabels(ks)
    a1.set_xlabel("active Kenyon cells k")
    a1.set_ylabel("mean average precision")
    a1.set_title("Fly hash versus Gaussian sign codes", color=_INK, fontsize=9.5, loc="left")
    a1.grid(axis="y", color="#ecebe6", lw=0.7)
    a1.set_axisbelow(True)

    null = np.array(pr["null_scores"])
    real = np.array(pr["real_scores"])
    rng = np.random.default_rng(0)
    for i, k in enumerate(pr["sizes"]):
        rel = 100 * (null[:, i] / null[:, i].mean() - 1)
        xs = i + rng.uniform(-0.28, 0.28, len(rel))
        a2.scatter(xs, rel, s=5, color=_ORANGE, alpha=0.35, linewidths=0)
        r = 100 * (real[i] / null[:, i].mean() - 1)
        a2.scatter([i], [r], s=46, color=_BLUE, marker="D", edgecolors=_SURFACE,
                   linewidths=0.9, zorder=3)
        row = pr["rows"][i]
        a2.annotate(f"p={row['randomization']['p_two_sided']:.2f}", (i, r),
                    xytext=(0, -13), textcoords="offset points", ha="center",
                    fontsize=6.5, color=_BLUE)
    a2.axhline(0, color="#9a9992", lw=0.9)
    a2.set_xticks(range(len(pr["sizes"])))
    a2.set_xticklabels([f"{k}{'*' if k == pr['primary_k'] else ''}" for k in pr["sizes"]])
    a2.set_xlabel("active Kenyon cells k   (* primary)")
    a2.set_ylabel("mAP relative to null mean (%)")
    a2.set_title(f"Measured wiring among {pr['B']} curveball nulls",
                 color=_INK, fontsize=9.5, loc="left")
    a2.grid(axis="y", color="#ecebe6", lw=0.7)
    a2.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


# ------------------------------------------------------------------ LaTeX

def _mac(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def latex(pr, ar, cv, rb, co) -> str:
    P = pr["projection"]
    row = _primary_row(pr)
    boot = pr["bootstrap"]
    lo, hi = boot["relative_ci"]
    mac = [
        "% Generated by `python -m flypath report` from results/*.json. Do not edit.",
        _mac("NullB", pr["B"]), _mac("BootR", boot["draws"]),
        _mac("NItems", f"{pr['n_items']:,}".replace(",", "{,}")),
        _mac("PrimaryK", pr["primary_k"]),
        _mac("NGlomFull", P["n_glomeruli_full"]),
        _mac("NCellsFull", f"{P['n_cells_full']:,}".replace(",", "{,}")),
        _mac("NGlom", P["n_glomeruli"]),
        _mac("NCells", f"{P['n_cells']:,}".replace(",", "{,}")),
        _mac("NNZ", f"{P['nnz']:,}".replace(",", "{,}")),
        _mac("InputsFull", f"{P['inputs_mean_full']:.2f}"),
        _mac("Inputs", f"{P['inputs_mean']:.2f}"),
        _mac("PNPartners", f"{P['pn_partners_mean']:.2f}"),
        _mac("FanMin", P["fan_out_min"]), _mac("FanMax", P["fan_out_max"]),
        _mac("FanMaxGlom", P["fan_out_max_glomerulus"]),
        _mac("NOdorants", P["n_odorants"]),
        _mac("MissingPct", f"{100 * P['missing_fraction']:.1f}\\%"),
        _mac("DoorCommit", P["door_commit"][:7]),
        _mac("PrimaryReal", f"{row['real']:.4f}"),
        _mac("PrimaryNullMean", f"{row['null_mean']:.4f}"),
        _mac("PrimaryNullSD", f"{row['null_sd']:.4f}"),
        _mac("PrimaryNullCV", f"{100 * row['null_cv']:.2f}\\%"),
        _mac("PrimaryNullSE", f"{row['null_se']:.5f}"),
        _mac("PrimaryRel", f"{pct(row['relative_difference'], 2)}\\%"),
        _mac("PrimaryZ", f"{row['z']:+.2f}"),
        _mac("PrimaryPtwo", pval(row["randomization"]["p_two_sided"])),
        _mac("PrimaryPlower", pval(row["randomization"]["p_lower"])),
        _mac("PrimaryRank", row["randomization"]["rank_from_top"]),
        _mac("BootLo", f"{pct(lo, 1)}\\%"), _mac("BootHi", f"{pct(hi, 1)}\\%"),
        _mac("EquivPrimary", "holds" if boot["equivalent"][f"{boot['primary_margin']:.3f}"]
             else "does not hold"),
        _mac("MarginPrimary", f"{100 * boot['primary_margin']:.0f}\\%"),
        _mac("MdeUp", f"{100 * pr['power']['mde80_upper']:.1f}\\%" if pr["power"]["mde80_upper"] else "n/a"),
        _mac("MdeDown", f"{100 * abs(pr['power']['mde80_lower']):.1f}\\%" if pr["power"]["mde80_lower"] else "n/a"),
        _mac("MinHolm", pval(min(r["randomization"]["p_two_sided_holm"]
                                 for r in pr["rows"] if not r["primary"]))),
        _mac("SecPMin", pval(min(r["randomization"]["p_two_sided"] for r in pr["rows"] if not r["primary"]))),
        _mac("SecPMax", pval(max(r["randomization"]["p_two_sided"] for r in pr["rows"] if not r["primary"]))),
        _mac("SecRelMin", f"{pct(min(r['relative_difference'] for r in pr['rows'] if not r['primary']), 1)}\\%"),
        _mac("SecRelMax", f"{pct(max(r['relative_difference'] for r in pr['rows'] if not r['primary']), 1)}\\%"),
        _mac("EquivTwoFive", "holds" if boot["equivalent"]["0.025"] else "does not hold"),
        _mac("NullsAbove", row["randomization"]["rank_from_top"] - 1),
        _mac("TieConflictMax", f"{100 * max(r['tie_conflict_fraction'] for r in pr['rows']):.1f}\\%"),
    ]
    if cv:
        t = cv["real_q_test"]
        mac += [_mac("QRealP", pval(t["p_upper"])),
                _mac("QRealRel", f"{pct(cv['real_q'] / cv['pool_q_mean'] - 1, 1)}\\%"),
                _mac("PlateauSweeps", _plateau(cv)),
                _mac("JaccardPlateau", _jaccard_plateau(cv)[0]),
                _mac("JaccardFinal", f"{_jaccard_plateau(cv)[1]:.3f}")]
    if co:
        ts, old = co["two_stage"], co["superseded_group_bootstrap"]
        mac += [_mac("CovNew", f"{100 * ts['coverage']:.0f}\\%"),
                _mac("CovNewLo", f"{100 * ts['wilson95'][0]:.0f}"),
                _mac("CovNewHi", f"{100 * ts['wilson95'][1]:.0f}"),
                _mac("CovOld", f"{100 * old['coverage']:.0f}\\%"),
                _mac("CovOldLo", f"{100 * old['wilson95'][0]:.0f}"),
                _mac("CovOldHi", f"{100 * old['wilson95'][1]:.0f}"),
                _mac("CovDatasets", co["datasets"]), _mac("CovItems", co["n_items"])]
    if rb:
        rels, ps, n_sig = [], [], 0
        for c in rb["rows"]:
            pk = next(k for k in c["per_k"] if k["primary"])
            rels.append(pk["relative_difference"])
            ps.append(pk["p_two_sided"])
            n_sig += pk["p_two_sided"] < 0.05
        by = {c["id"]: next(k for k in c["per_k"] if k["primary"]) for c in rb["rows"]}
        imp = [by[i] for i in ("missing_glomerulus_mean", "missing_odour_mean", "missing_lowrank") if i in by]
        pmin_attainable = 2 / (rb["B"] + 1)
        mac += [_mac("RobNNeg", sum(r < 0 for r in rels)),
                _mac("RobNAtMin", sum(p <= pmin_attainable + 1e-12 for p in ps)),
                _mac("RobPFloor", pval(pmin_attainable))]
        if imp:
            mac += [_mac("ImputeRelMin", f"{pct(min(r['relative_difference'] for r in imp), 1)}\\%"),
                    _mac("ImputeRelMax", f"{pct(max(r['relative_difference'] for r in imp), 1)}\\%"),
                    _mac("ImputePMin", pval(min(r["p_two_sided"] for r in imp)))]
        mac += [_mac("RobN", len(rb["rows"])), _mac("RobB", rb["B"]),
                _mac("RobRelMin", f"{pct(min(rels), 1)}\\%"),
                _mac("RobRelMax", f"{pct(max(rels), 1)}\\%"),
                _mac("RobNSig", n_sig), _mac("RobMinP", pval(min(ps)))]
    if ar:
        m = ar["metrics"]["euclidean"]
        i = m["sizes"].index(pr["primary_k"])
        for key, name in (("k_bits", "Kbits"), ("storage_matched", "Storage"),
                          ("computation_matched", "Compute")):
            mac.append(_mac(f"Arch{name}Ratio", f"{m['gaussian'][key]['ratio_fly_over'][i]:.2f}"))
        mac.append(_mac("StorageBitsPrimary", ar["budgets"]["storage_matched"][str(pr["primary_k"])]))
        mac.append(_mac("ComputeBits", ar["budgets"]["computation_matched"][str(pr["primary_k"])]))

    # Table: wiring comparison
    wt = []
    for r in pr["rows"]:
        a = r["alternatives"]
        star = "$^\\ast$" if r["primary"] else ""
        wt.append(f"{r['k']}{star} & {r['real']:.4f} & {r['null_mean']:.4f} $\\pm$ {r['null_sd']:.4f} & "
                  f"{pct(r['relative_difference'], 1)} & {pval(r['randomization']['p_two_sided'])} & "
                  f"{'--' if r['primary'] else pval(r['randomization']['p_two_sided_holm'])} & "
                  f"{pct(a['shuffle_inputs']['relative_to_null'], 1)} & "
                  f"{pct(a['uniform_inputs_6']['relative_to_null'], 1)} & "
                  f"{pct(a['balanced_fanout']['relative_to_null'], 1)} \\\\")
    mac.append("\\newcommand{\\WiringRows}{" + "\n".join(wt) + "}")

    # Table: architecture
    if ar:
        m = ar["metrics"]["euclidean"]
        at = []
        for i, k in enumerate(m["sizes"]):
            g = m["gaussian"]
            at.append(f"{k} & {m['fly'][i]:.3f} & {g['k_bits']['mean'][i]:.3f} & "
                      f"{g['storage_matched']['mean'][i]:.3f} ({ar['budgets']['storage_matched'][str(k)]}) & "
                      f"{g['computation_matched']['mean'][i]:.3f} ({ar['budgets']['computation_matched'][str(k)]}) \\\\")
        mac.append("\\newcommand{\\ArchRows}{" + "\n".join(at) + "}")

    # Table: robustness summary by family
    if rb:
        fam = [("Baseline", ["baseline"]),
               ("Left hemisphere", ["hemisphere_L"]),
               ("$\\geq$5-synapse threshold", ["synapse_threshold_5"]),
               ("Missing data (3 imputations)", ["missing_glomerulus_mean", "missing_odour_mean", "missing_lowrank"]),
               ("Coverage thresholds (2)", ["coverage_strict", "coverage_loose"]),
               ("All 46 glomeruli with data, imputed", ["all_glomeruli"]),
               ("Mixture seeds (4)", ["mixture_seed_1", "mixture_seed_2", "mixture_seed_3", "mixture_seed_4"]),
               ("Mixture size 2 / 2--10", ["mixtures_pairs", "mixtures_wide"]),
               ("Measured odorants only", ["measured_only"]),
               ("Normalised / angular metric", ["metric_normalised", "metric_angular"]),
               ("Tie rules (index, include, 2 seeds)", ["ties_index", "ties_include", "tie_seed_1", "tie_seed_2"]),
               ("Synapse-weighted", ["weighted"]),
               ("Synthetic inputs (3)", ["synthetic_lowrank", "synthetic_gaussian", "synthetic_sparse"])]
        by = {c["id"]: c for c in rb["rows"]}
        rt = []
        for label, ids in fam:
            rows = [next(k for k in by[i]["per_k"] if k["primary"]) for i in ids if i in by]
            if not rows:
                continue
            rels = [r["relative_difference"] for r in rows]
            ps = [r["p_two_sided"] for r in rows]
            lo_r, hi_r = pct(min(rels), 1), pct(max(rels), 1)
            rel = lo_r if lo_r == hi_r else f"{lo_r} to {hi_r}"
            lo_p, hi_p = pval(min(ps)), pval(max(ps))
            p = lo_p if lo_p == hi_p else f"{lo_p}--{hi_p}"
            rt.append(f"{label} & {rel} & {p} \\\\")
        mac.append("\\newcommand{\\RobRows}{" + "\n".join(rt) + "}")
    mac += _benchmark_macros(_load("replication.json"), _load("connectome_benchmarks.json"))
    return "\n".join(mac) + "\n"


_NAMES = {"sift": "SIFT", "glove": "GloVe", "mnist": "MNIST"}


def _benchmark_macros(rp, cb) -> list[str]:
    """The 2017 benchmarks: replication with random matrices (ReplRows) and
    the measured wiring on the same data (ConnRows)."""
    mac = []
    if rp:
        ks = rp["protocol"]["hash_lengths"]
        rows = []
        for name, r in rp["datasets"].items():
            for k in (4, 16):
                i = ks.index(k)
                f = {key: r[key]["map"]["mean"][i] for key in ("lsh", "random_20k", "fly_20k", "fly_10d")}
                rows.append(f"{_NAMES[name]} & {k} & {f['lsh']:.3f} & {f['random_20k']:.3f} & "
                            f"{f['fly_20k']:.3f} & {f['fly_10d']:.3f} & "
                            f"{f['fly_10d'] / f['lsh']:.1f}$\\times$ \\\\")
        mac.append("\\newcommand{\\ReplRows}{" + "\n".join(rows) + "}")
        i4 = ks.index(4)
        mn, sf = rp["datasets"].get("mnist"), rp["datasets"].get("sift")
        if mn:
            lsh, fly = mn["lsh"]["map"]["mean"][i4], mn["fly_10d"]["map"]["mean"][i4]
            mac += [_mac("ReplMnistLsh", f"{lsh:.3f}"), _mac("ReplMnistFly", f"{fly:.3f}"),
                    _mac("ReplMnistRatio", f"{fly / lsh:.1f}"),
                    _mac("ReplOpsBitsMnist", mn["lsh_ops_10d_bits"])]
        if sf:
            mac += [_mac("ReplSiftRandom", f"{sf['random_20k']['map']['mean'][i4]:.3f}"),
                    _mac("ReplSiftWta", f"{sf['fly_20k']['map']['mean'][i4]:.3f}")]
        ops = [r["lsh_ops_10d"]["map"]["mean"] for r in rp["datasets"].values()]
        fly32 = [r["fly_10d"]["map"]["mean"][ks.index(32)] for r in rp["datasets"].values()]
        mac += [_mac("ReplTrials", rp["protocol"]["trials"]),
                _mac("ReplOpsMin", f"{min(ops):.2f}"), _mac("ReplOpsMax", f"{max(ops):.2f}"),
                _mac("ReplFlyMax", f"{max(fly32):.2f}")]
    if cb:
        big = max(cb["sizes"])
        rows = []
        for name, per in cb["datasets"].items():
            for r in per["map"]["rows"]:
                if r["k"] in (4, 16, big):
                    rows.append(f"{_NAMES[name]} & {r['k']} & {r['real']:.3f} & {r['null_mean']:.3f} & "
                                f"{pct(r['relative_difference'], 1)} & {pval(r['p_two_sided'])} & "
                                f"{r['random_2017']:.3f} & {r['lsh']:.3f} \\\\")
        mac.append("\\newcommand{\\ConnRows}{" + "\n".join(rows) + "}")
        allr = [r for per in cb["datasets"].values() for r in per["map"]["rows"]]
        ops = [per["map"]["lsh_ops"] for per in cb["datasets"].values()]
        flybig = [next(r for r in per["map"]["rows"] if r["k"] == big)["real"]
                  for per in cb["datasets"].values()]
        mac += [_mac("ConnB", cb["B"]), _mac("ConnTrials", cb["trials"]),
                _mac("ConnGlom", cb["n_glomeruli"]),
                _mac("ConnCells", f"{cb['n_cells']:,}".replace(",", "{,}")),
                _mac("ConnBigK", big),
                _mac("ConnRelMin", f"{pct(min(r['relative_difference'] for r in allr), 1)}\\%"),
                _mac("ConnRelMax", f"{pct(max(r['relative_difference'] for r in allr), 1)}\\%"),
                _mac("ConnPMin", pval(min(r["p_two_sided"] for r in allr))),
                _mac("ConnNSig", sum(r["p_two_sided"] < 0.05 for r in allr)),
                _mac("ConnNTests", len(allr)),
                _mac("ConnOpsBits", cb["lsh_ops_matched_bits"]),
                _mac("ConnOpsMin", f"{min(ops):.2f}"), _mac("ConnOpsMax", f"{max(ops):.2f}"),
                _mac("ConnFlyBigMin", f"{min(flybig):.2f}"), _mac("ConnFlyBigMax", f"{max(flybig):.2f}"),
                _mac("ConnRandGainMax", f"{100 * max(r['random_2017'] / r['real'] - 1 for r in allr):.0f}\\%")]
        mn = cb["datasets"].get("mnist")
        if mn:
            r4 = next(r for r in mn["map"]["rows"] if r["k"] == 4)
            mac += [_mac("ConnMnistReal", f"{r4['real']:.3f}"), _mac("ConnMnistLsh", f"{r4['lsh']:.3f}"),
                    _mac("ConnMnistRatio", f"{r4['real'] / r4['lsh']:.1f}")]
    return mac


def _benchmark_supplement(rp, cb) -> list[str]:
    L = []
    if rp:
        pc = rp["protocol"]
        L += ["## The 2017 benchmarks with random matrices (replication)", "",
              f"{pc['n']} vectors per dataset, {pc['queries']} queries, top {100 * pc['top']:.0f}% "
              f"neighbours, {pc['trials']} trials; each Kenyon cell samples {100 * pc['sampling']:.0f}% "
              "of the inputs. Mean (SD over trials). Reported in the 2017 paper: MNIST k=4 LSH 0.160, "
              "fly (m=10d) 0.448; SIFT k=4 random selection 0.177, WTA (m=20k) 0.324.", ""]
        for met, title in (("map", "mean average precision (standard definition)"),
                           ("overlap", "list overlap (FlyLSH reference code)")):
            L += [f"### {title}", "",
                  "| dataset | k | LSH | sign LSH | random 20k | fly 20k | fly 10d |",
                  "|---|---|---|---|---|---|---|"]
            for name, r in rp["datasets"].items():
                for i, k in enumerate(pc["hash_lengths"]):
                    c = {key: f"{r[key][met]['mean'][i]:.3f} ({r[key][met]['sd'][i]:.3f})"
                         for key in ("lsh", "lsh_sign", "random_20k", "fly_20k", "fly_10d")}
                    L.append(f"| {_NAMES[name]} | {k} | {c['lsh']} | {c['lsh_sign']} | "
                             f"{c['random_20k']} | {c['fly_20k']} | {c['fly_10d']} |")
            L += ["", "LSH given the operation count of the m = 10d fly (10d cells x 0.1d additions "
                      "= 2d operations x d/2 projections):", ""]
            for name, r in rp["datasets"].items():
                L.append(f"- {_NAMES[name]}: {r['lsh_ops_10d_bits']} projections, "
                         f"{r['lsh_ops_10d'][met]['mean']:.3f} ({r['lsh_ops_10d'][met]['sd']:.3f})")
            L.append("")
    if cb:
        L += ["## The measured wiring on the 2017 benchmarks", "",
              f"Each dataset reduced by PCA to {cb['n_glomeruli']} components (one per glomerulus, "
              f"assigned at random in each trial); {cb['n_cells']} Kenyon cells, {cb['trials']} trials, "
              f"{cb['B']} curveball nulls, each matrix's score averaged over trials. "
              f"'2017 random': every cell samples 6 of the {cb['n_glomeruli']} glomeruli.", ""]
        for met in ("map", "overlap"):
            L += [f"### {met}", "",
                  "| dataset | k | measured | null mean +/- SD | rel. diff. | p | 2017 random | LSH | sign LSH |",
                  "|---|---|---|---|---|---|---|---|---|"]
            for name, per in cb["datasets"].items():
                for r in per[met]["rows"]:
                    L.append(f"| {_NAMES[name]} | {r['k']} | {r['real']:.4f} | {r['null_mean']:.4f} +/- "
                             f"{r['null_sd']:.4f} | {pct(r['relative_difference'], 2)}% | "
                             f"{pval(r['p_two_sided'])} | {r['random_2017']:.4f} | {r['lsh']:.4f} | "
                             f"{r['lsh_sign']:.4f} |")
                L.append(f"| {_NAMES[name]} | LSH, matched operations ({cb['lsh_ops_matched_bits']} "
                         f"projections) | {per[met]['lsh_ops']:.4f} | | | | | | |")
            L.append("")
    return L


def _plateau(cv: dict, tol_sd: float = 3.0) -> str:
    """First checkpoint from which every chain's co-occurrence statistic stays
    inside `tol_sd` standard deviations of the null distribution (200
    independent draws). Single stationary draws fall outside one SD about a
    third of the time, so a one-SD criterion is never met; three is the
    appropriate envelope for individual values."""
    mu, sd = cv["pool_q_mean"], cv["pool_q_sd"]
    marks = cv["marks"]
    for j, mk in enumerate(marks):
        if all(abs(ch[i]["cooccurrence_q"] - mu) <= tol_sd * sd
               for ch in cv["chains"] for i in range(j, len(marks))):
            return f"{mk:g}"
    return "n/a"


def _jaccard_plateau(cv: dict, tol: float = 0.005) -> tuple[str, float]:
    """First checkpoint from which the mean Jaccard overlap with the measured
    matrix stays within `tol` of its value at the last checkpoint."""
    marks = cv["marks"]
    mean = [np.mean([ch[j]["jaccard_to_real"] for ch in cv["chains"]]) for j in range(len(marks))]
    final = mean[-1]
    for j, mk in enumerate(marks):
        if all(abs(v - final) <= tol for v in mean[j:]):
            return f"{mk:g}", float(final)
    return "n/a", float(final)


# ------------------------------------------------------------------ supplement

def supplement(pr, ar, cv, rb, co) -> str:
    L = ["# Supplement: full results", "",
         "Generated by `python -m flypath report` from `results/*.json`. Every table in the",
         "paper is a subset of what is here.", ""]
    if rb:
        L += [f"## Robustness grid ({rb['B']} curveball nulls per condition)", "",
              "Relative mAP difference (measured wiring vs null mean) and two-sided randomization p,",
              "for the primary hash size (5% of Kenyon cells) and every secondary size.", ""]
        ks = sorted({k["k"] for c in rb["rows"] for k in c["per_k"] if not k["primary"]})
        L.append("| condition | items | glom. | cells | primary k: rel. diff | p | "
                 + " | ".join(f"k={k}: rel / p" for k in ks) + " |")
        L.append("|---|---|---|---|---|---|" + "---|" * len(ks))
        for c in rb["rows"]:
            pk = next(k for k in c["per_k"] if k["primary"])
            sec = {k["k"]: k for k in c["per_k"] if not k["primary"]}
            L.append(f"| {c['label']} | {c['n_items']} | {c['n_glomeruli']} | {c['n_cells']} | "
                     f"{pct(pk['relative_difference'], 2)}% (k={pk['k']}) | {pval(pk['p_two_sided'])} | "
                     + " | ".join(f"{pct(sec[k]['relative_difference'], 1)}% / {pval(sec[k]['p_two_sided'])}"
                                  if k in sec else "" for k in ks) + " |")
        L.append("")
    if pr:
        L += ["## Power of the randomization test (primary hash size)", "",
              "Shift model: the measured wiring behaves like a random wiring whose score is",
              "multiplied by (1 + delta); rejection rate at alpha = 0.05 against the empirical null.", "",
              "| delta | power (one-sided) |", "|---|---|"]
        for d, v in {**pr["power"]["lower"], **pr["power"]["upper"]}.items():
            L.append(f"| {pct(float(d), 1)}% | {v:.2f} |")
        L += ["", f"80% power reached at {pct(pr['power']['mde80_lower'] or 0, 1)}% (worse) and "
                  f"{pct(pr['power']['mde80_upper'] or 0, 1)}% (better).", ""]
        b = pr["bootstrap"]
        L += ["## Equivalence", "",
              f"Two-stage bootstrap ({b['draws']} replicates) 90% interval for the relative difference: "
              f"[{pct(b['relative_ci'][0], 2)}%, {pct(b['relative_ci'][1], 2)}%].", "",
              "| margin | equivalent (TOST, alpha = 0.05 per side) |", "|---|---|"]
        for mg, ok in b["equivalent"].items():
            L.append(f"| +/-{100 * float(mg):.1f}% | {'yes' if ok else 'no'} |")
        L.append("")
    if co:
        L += ["## Coverage of the interval procedures", "",
              f"{co['datasets']} datasets drawn from a rank-6 generative model fitted to the source "
              f"profiles; {co['n_items']} items each; k = {co['k']}; nominal 90%.", "",
              "| procedure | coverage | Wilson 95% | median width |", "|---|---|---|---|"]
        for key, name in (("two_stage", "two-stage bootstrap (this revision)"),
                          ("superseded_group_bootstrap", "group bootstrap (previous revision)")):
            c = co[key]
            L.append(f"| {name} | {100 * c['coverage']:.0f}% | {100 * c['wilson95'][0]:.0f}-"
                     f"{100 * c['wilson95'][1]:.0f}% | {100 * c['median_width']:.2f} pp |")
        L.append("")
    if cv:
        L += ["## Curveball mixing", "",
              "Glomerulus co-occurrence statistic Q and Jaccard overlap with the measured matrix, "
              "per chain and checkpoint.", "",
              f"Reference (200 pool nulls at 30 sweeps): Q = {cv['pool_q_mean']:.0f} +/- {cv['pool_q_sd']:.0f}; "
              f"measured matrix Q = {cv['real_q']:.0f} (upper-tail p = {pval(cv['real_q_test']['p_upper'])}).", "",
              "| sweeps | " + " | ".join(f"chain {i + 1} Q" for i in range(len(cv["chains"]))) + " | mean Jaccard |",
              "|---|" + "---|" * (len(cv["chains"]) + 1)]
        for j, mk in enumerate(cv["marks"]):
            qs = [ch[j]["cooccurrence_q"] for ch in cv["chains"]]
            jac = np.mean([ch[j]["jaccard_to_real"] for ch in cv["chains"]])
            L.append(f"| {mk:g} | " + " | ".join(f"{q:.0f}" for q in qs) + f" | {jac:.3f} |")
        L += ["", "mAP at the primary hash size along the chains:", "",
              "| sweeps | " + " | ".join(f"chain {i + 1}" for i in range(len(cv["chains"]))) + " |",
              "|---|" + "---|" * len(cv["chains"])]
        for j, mk in enumerate(cv["marks"]):
            vals = [ch[j]["map"] for ch in cv["chains"]]
            if all(v is not None for v in vals):
                L.append(f"| {mk:g} | " + " | ".join(f"{v:.4f}" for v in vals) + " |")
        L.append("")
    if ar:
        L += ["## Architecture comparison under all three ground truths", ""]
        for metric, m in ar["metrics"].items():
            L += [f"### {metric}", "", "| k | fly | Gaussian k bits | storage-matched | computation-matched |",
                  "|---|---|---|---|---|"]
            for i, k in enumerate(m["sizes"]):
                g = m["gaussian"]
                L.append(f"| {k} | {m['fly'][i]:.4f} | {g['k_bits']['mean'][i]:.4f} "
                         f"({g['k_bits']['ratio_fly_over'][i]:.2f}x) | "
                         f"{g['storage_matched']['mean'][i]:.4f} ({g['storage_matched']['ratio_fly_over'][i]:.2f}x) | "
                         f"{g['computation_matched']['mean'][i]:.4f} ({g['computation_matched']['ratio_fly_over'][i]:.2f}x) |")
            L.append("")
        L += [f"Budgets (bits): k-bit = k; storage-matched = ceil(log2 C(m, k)); computation-matched = "
              f"round(nnz / 2d) = {ar['budgets']['computation_matched'][str(pr['primary_k'])]}, "
              f"counting operations as Dasgupta et al. (2017) do (d multiplications plus d additions "
              f"per Gaussian projection, one addition per non-zero of M). "
              f"Ratios are fly / Gaussian.", ""]
    L += _benchmark_supplement(_load("replication.json"), _load("connectome_benchmarks.json"))
    return "\n".join(L)


# ------------------------------------------------------------------ README block

def readme_block(pr, ar, rb, co) -> str:
    row = _primary_row(pr)
    b = pr["bootstrap"]
    m = ar["metrics"]["euclidean"] if ar else None
    L = ["<!-- results:start (generated by `python -m flypath report`; do not edit) -->", "",
         f"Primary hash size k = {pr['primary_k']} (5% of {pr['projection']['n_cells']} Kenyon cells), "
         f"{pr['n_items']} synthetic mixtures, {pr['B']} curveball nulls:", "",
         "| k | measured | null mean +/- SD | rel. diff. | p (two-sided) | p (Holm) |",
         "|---|---|---|---|---|---|"]
    for r in pr["rows"]:
        holm = "(primary, not adjusted)" if r["primary"] else pval(r["randomization"]["p_two_sided_holm"])
        L.append(f"| {r['k']}{' (primary)' if r['primary'] else ''} | {r['real']:.4f} | "
                 f"{r['null_mean']:.4f} +/- {r['null_sd']:.4f} | {pct(r['relative_difference'], 2)}% | "
                 f"{pval(r['randomization']['p_two_sided'])} | {holm} |")
    equiv = b["equivalent"][f"{b['primary_margin']:.3f}"]
    L += ["", f"Two-stage bootstrap 90% interval for the relative difference at the primary size: "
              f"[{pct(b['relative_ci'][0], 1)}%, {pct(b['relative_ci'][1], 1)}%]; "
              f"equivalence at the pre-specified +/-{100 * b['primary_margin']:.0f}% margin: "
              f"{'yes' if equiv else 'no'}."]
    if m:
        i = m["sizes"].index(pr["primary_k"])
        g = m["gaussian"]
        L += ["", f"Fly hash / Gaussian sign code at k = {pr['primary_k']}: "
                  f"{g['k_bits']['ratio_fly_over'][i]:.2f}x at k bits, "
                  f"{g['storage_matched']['ratio_fly_over'][i]:.2f}x at matched storage "
                  f"({ar['budgets']['storage_matched'][str(pr['primary_k'])]} bits), "
                  f"{g['computation_matched']['ratio_fly_over'][i]:.2f}x at matched operations "
                  f"({ar['budgets']['computation_matched'][str(pr['primary_k'])]} bits)."]
    rp, cb = _load("replication.json"), _load("connectome_benchmarks.json")
    if rp and "mnist" in rp["datasets"]:
        mn = rp["datasets"]["mnist"]
        i4 = rp["protocol"]["hash_lengths"].index(4)
        L += ["", f"2017 protocol with random matrices, MNIST, k = 4: LSH {mn['lsh']['map']['mean'][i4]:.3f} "
                  f"(reported 0.160), fly hash {mn['fly_10d']['map']['mean'][i4]:.3f} (reported 0.448)."]
    if cb:
        allr = [r for per in cb["datasets"].values() for r in per["map"]["rows"]]
        L += ["", f"Measured wiring on SIFT, GloVe and MNIST (PCA to {cb['n_glomeruli']} inputs): "
                  f"{pct(min(r['relative_difference'] for r in allr), 1)}% to "
                  f"{pct(max(r['relative_difference'] for r in allr), 1)}% relative to "
                  f"{cb['B']} curveball nulls across {len(allr)} dataset-size combinations."]
    if co:
        L += ["", f"Coverage of the 90% interval in simulation: "
                  f"{100 * co['two_stage']['coverage']:.0f}% (previous procedure: "
                  f"{100 * co['superseded_group_bootstrap']['coverage']:.0f}%)."]
    if rb:
        L += ["", f"Robustness: {len(rb['rows'])} one-factor variations, see "
                  f"[results/SUPPLEMENT.md](results/SUPPLEMENT.md)."]
    L += ["", "<!-- results:end -->"]
    return "\n".join(L)


# ------------------------------------------------------------------ checksums

def verify_checksums(cfg) -> bool:
    from .flyhash import sha256
    ok = True
    for line in (ROOT / "DATA_CHECKSUMS.txt").read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        h, name = line.split(None, 1)
        f = cfg.raw_dir / name
        got = sha256(f) if f.exists() else "missing"
        match = got == h
        ok &= match
        print(f"{'ok  ' if match else 'FAIL'}  {name}")
    return ok


# ------------------------------------------------------------------ all

def build_all() -> None:
    pr, ar = _load("primary.json"), _load("architecture.json")
    cv, rb, co = _load("convergence.json"), _load("robustness.json"), _load("coverage.json")
    if not pr:
        raise SystemExit("results/primary.json missing; run: python -m flypath analyse")
    figure(pr, ar, RES / "flyhash.png")
    (ROOT / "paper" / "generated.tex").write_text(latex(pr, ar, cv, rb, co))
    (RES / "SUPPLEMENT.md").write_text(supplement(pr, ar, cv, rb, co))
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- results:start", "<!-- results:end -->"
    if start in text and end in text:
        a = text.index(start)
        b = text.index(end) + len(end)
        readme.write_text(text[:a] + readme_block(pr, ar, rb, co) + text[b:])
    print("wrote results/flyhash.png, paper/generated.tex, results/SUPPLEMENT.md, README block")
